channels:
  - "UCO97Xw-M_xPjUAdp2pFamYg" # @masajinobe
  - "UCVJiYZ7oiHdBnkkOoSrse3Q" # @priscilla_eF
  - "UCWxFYv7xfPQVx5yzjpJX33w" # @sigureSMEJ
  - "UCXiquZudn24_WwguvUxr4TQ" # @roshiajinn12cm
  - "UC5fTXIeWfJJmqNchJBgPdSQ" # @kolyalut
  - "UCXaBEZXBgYbGQcGYlqaLOUw" # @HeroGriefer
